apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: meu-pod
  name: meu-pod
spec:
  containers:
  - image: nginx
    name: meu-pod
    resources: {}
  nodeSelector:
    disktype: ssd
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
