apiVersion: v1
kind: Pod
metadata:
  name: test-secret-env
  namespace: default
spec:
  containers:
  - image: busybox
    name: busy
    command: 
      - sleep
      - "3600"
    env:
    - name: USERNAME
      valueFrom: 
        secretKeyRef:
          name: my-secret
          key: user
    - name: PASSWORD
      valueFrom: 
        secretKeyRef:
          name: my-secret
          key: password
        