apiVersion: v1
kind: Pod
metadata:
  name: nginx-configmap
  namespace: default
spec:
  containers:
  - image: nginx
    name: nginx-configmap
    env:
    - name: USER
      valueFrom:
        configMapKeyRef:
          name: credenciais
          key: user
    - name: PASSWORD
      valueFrom:
        configMapKeyRef:
          name: credenciais
          key: password