apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: meu-deployment
  name: meu-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: meu-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: meu-deployment
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
