apiVersion: v1
kind: Pod
metadata:
  name: meu-pod
spec:
  containers:
  - image: nginx
    name: nginx-container-01
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  - image: busybox
    name: nginx-container-02
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}