apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: meu-pod
  name: meu-pod
spec:
  containers:
  - image: nginx
    name: meu-pod
    env:
    - name: NGINX_PORT
      value: "80"
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
